param(
    [string]$KeystorePath = "$env:USERPROFILE\.android\keystore\monadbox-release.jks",
    [string]$Alias = "monadbox-release",
    [int]$ValidityDays = 10000,
    [string]$StoreType = "PKCS12",
    [switch]$ForceRegenerate,
    [switch]$SkipBuild,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

function Get-PlainTextFromSecureString {
    param([System.Security.SecureString]$Secure)
    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($Secure)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
    } finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
    }
}

$projectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $projectRoot

if (-not (Get-Command keytool -ErrorAction SilentlyContinue)) {
    throw "keytool not found. Install JDK and ensure keytool is available in PATH."
}

if (-not (Test-Path -LiteralPath (Join-Path $projectRoot "gradlew.bat"))) {
    throw "gradlew.bat not found in repository root."
}

$keystoreFullPath = [System.IO.Path]::GetFullPath($KeystorePath)
$keystoreDir = Split-Path -Parent $keystoreFullPath
if (-not (Test-Path -LiteralPath $keystoreDir)) {
    New-Item -ItemType Directory -Path $keystoreDir -Force | Out-Null
}

$shouldCreate = $true
if ((Test-Path -LiteralPath $keystoreFullPath) -and -not $ForceRegenerate) {
    Write-Host "[signing-setup] Keystore already exists, skip generate: $keystoreFullPath"
    $shouldCreate = $false
}

$storePasswordSecure = Read-Host "Enter keystore password" -AsSecureString
$keyPasswordSecure = Read-Host "Enter key password (can be same as keystore password)" -AsSecureString
$storePassword = Get-PlainTextFromSecureString -Secure $storePasswordSecure
$keyPassword = Get-PlainTextFromSecureString -Secure $keyPasswordSecure

if ([string]::IsNullOrWhiteSpace($storePassword)) {
    throw "Keystore password cannot be empty."
}
if ([string]::IsNullOrWhiteSpace($keyPassword)) {
    throw "Key password cannot be empty."
}

$signingPropertiesPath = Join-Path $projectRoot "signing.properties"
$keystorePathForProperties = $keystoreFullPath -replace '\\', '/'
$lines = @(
    "# Auto-generated by scripts/setup-release-signing.ps1",
    "# Do NOT commit this file with real credentials.",
    "keystore.path=$keystorePathForProperties",
    "keystore.password=$storePassword",
    "key.alias=$Alias",
    "key.password=$keyPassword"
)

$startupGatePath = Join-Path $projectRoot "startup-gate.local.properties"
$startupGateFingerprintPreview = "<SHA256_FROM_KEYSTORE>"
if (Test-Path -LiteralPath $keystoreFullPath) {
    $previewOutput = & keytool -list -v -keystore $keystoreFullPath -alias $Alias -storepass $storePassword 2>$null
    $previewFingerprint =
        ($previewOutput | Select-String -Pattern '^\s*SHA256:\s*(.+)$' | Select-Object -First 1)
            .Matches.Groups[1].Value.Trim()
    if (-not [string]::IsNullOrWhiteSpace($previewFingerprint)) {
        $startupGateFingerprintPreview = $previewFingerprint
    }
}

$startupGateLines = @(
    "# Auto-generated by scripts/setup-release-signing.ps1",
    "# Do NOT commit this file.",
    "startup.gate.expectedPackage=com.github.nomadboxlab.monadbox",
    "startup.gate.expectedAppClass=com.github.yumelira.yumebox.App",
    "startup.gate.expectedAppParent=android.app.Application",
    "startup.gate.releaseFingerprint=$startupGateFingerprintPreview",
    "startup.gate.enforceSigner=true",
    "startup.gate.enforceApkV2=true"
)

if ($DryRun) {
    Write-Host "[signing-setup] Dry-run mode: no file will be written and no build will run."
    Write-Host "[signing-setup] Target signing.properties path: $signingPropertiesPath"
    Write-Host "[signing-setup] Planned content:"
    $lines | ForEach-Object { Write-Host $_ }
    Write-Host "[signing-setup] Target startup-gate.local.properties path: $startupGatePath"
    Write-Host "[signing-setup] Planned content:"
    $startupGateLines | ForEach-Object { Write-Host $_ }
    if ($shouldCreate) {
        Write-Host "[signing-setup] Keystore generation would run for: $keystoreFullPath"
    } else {
        Write-Host "[signing-setup] Keystore generation would be skipped (file already exists)."
    }
    return
}

if ($shouldCreate) {
    $dName = "CN=MonadBox, OU=Mobile, O=NomadBoxLab, L=Unknown, S=Unknown, C=CN"
    Write-Host "[signing-setup] Generating keystore: $keystoreFullPath"
    & keytool -genkeypair -v `
        -keystore $keystoreFullPath `
        -storetype $StoreType `
        -alias $Alias `
        -keyalg RSA `
        -keysize 2048 `
        -validity $ValidityDays `
        -storepass $storePassword `
        -keypass $keyPassword `
        -dname $dName
}

Write-Host "[signing-setup] Validating keystore alias..."
$keytoolListOutput = & keytool -list -v -keystore $keystoreFullPath -alias $Alias -storepass $storePassword
$startupGateFingerprint =
    ($keytoolListOutput | Select-String -Pattern '^\s*SHA256:\s*(.+)$' | Select-Object -First 1)
        .Matches.Groups[1].Value.Trim()
if ([string]::IsNullOrWhiteSpace($startupGateFingerprint)) {
    throw "Failed to extract SHA256 fingerprint from keystore alias: $Alias"
}

$lines | Set-Content -Path $signingPropertiesPath -Encoding UTF8
Write-Host "[signing-setup] Wrote signing properties: $signingPropertiesPath"

$startupGateLines = @(
    "# Auto-generated by scripts/setup-release-signing.ps1",
    "# Do NOT commit this file.",
    "startup.gate.expectedPackage=com.github.nomadboxlab.monadbox",
    "startup.gate.expectedAppClass=com.github.yumelira.yumebox.App",
    "startup.gate.expectedAppParent=android.app.Application",
    "startup.gate.releaseFingerprint=$startupGateFingerprint",
    "startup.gate.enforceSigner=true",
    "startup.gate.enforceApkV2=true"
)
$startupGateLines | Set-Content -Path $startupGatePath -Encoding UTF8
Write-Host "[signing-setup] Wrote startup gate config: $startupGatePath"

if (-not $SkipBuild) {
    Write-Host "[signing-setup] Running release build validation..."
    & .\gradlew.bat :app:assembleRelease
}

Write-Host "[signing-setup] Done."
