#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

KEYSTORE_PATH="${HOME}/.android/keystore/monadbox-release.jks"
ALIAS="monadbox-release"
VALIDITY_DAYS=10000
STORE_TYPE="PKCS12"
FORCE_REGENERATE=false
SKIP_BUILD=false
DRY_RUN=false

usage() {
  cat <<'EOF'
Usage: ./scripts/setup-release-signing.sh [options]

Options:
  --keystore-path <path>   Keystore path (default: ~/.android/keystore/monadbox-release.jks)
  --alias <alias>          Key alias (default: monadbox-release)
  --validity-days <days>   Key validity in days (default: 10000)
  --store-type <type>      Keystore type (default: PKCS12)
  --force-regenerate       Regenerate keystore even if it already exists
  --skip-build             Skip release build validation
  --dry-run                Print planned signing.properties content without writing files
  -h, --help               Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --keystore-path)
      KEYSTORE_PATH="$2"
      shift 2
      ;;
    --alias)
      ALIAS="$2"
      shift 2
      ;;
    --validity-days)
      VALIDITY_DAYS="$2"
      shift 2
      ;;
    --store-type)
      STORE_TYPE="$2"
      shift 2
      ;;
    --force-regenerate)
      FORCE_REGENERATE=true
      shift
      ;;
    --skip-build)
      SKIP_BUILD=true
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

require_cmd keytool

if [[ ! -f "$PROJECT_ROOT/gradlew" ]]; then
  echo "gradlew not found in repository root." >&2
  exit 1
fi

mkdir -p "$(dirname "$KEYSTORE_PATH")"

STORE_PASSWORD=""
KEY_PASSWORD=""
read -r -s -p "Enter keystore password: " STORE_PASSWORD
echo
read -r -s -p "Enter key password (can be same as keystore password): " KEY_PASSWORD
echo

if [[ -z "$STORE_PASSWORD" ]]; then
  echo "Keystore password cannot be empty." >&2
  exit 1
fi
if [[ -z "$KEY_PASSWORD" ]]; then
  echo "Key password cannot be empty." >&2
  exit 1
fi

KEYSTORE_EXISTS=false
if [[ -f "$KEYSTORE_PATH" ]]; then
  KEYSTORE_EXISTS=true
fi

SHOULD_CREATE=true
if [[ "$KEYSTORE_EXISTS" == "true" && "$FORCE_REGENERATE" != "true" ]]; then
  echo "[signing-setup] Keystore already exists, skip generate: $KEYSTORE_PATH"
  SHOULD_CREATE=false
fi

SIGNING_PROPERTIES_PATH="$PROJECT_ROOT/signing.properties"
SIGNING_CONTENT=$(cat <<EOF
# Auto-generated by scripts/setup-release-signing.sh
# Do NOT commit this file with real credentials.
keystore.path=$KEYSTORE_PATH
keystore.password=$STORE_PASSWORD
key.alias=$ALIAS
key.password=$KEY_PASSWORD
EOF
)

STARTUP_GATE_PATH="$PROJECT_ROOT/startup-gate.local.properties"
STARTUP_GATE_FINGERPRINT_PREVIEW="<SHA256_FROM_KEYSTORE>"
if [[ -f "$KEYSTORE_PATH" ]]; then
  STARTUP_GATE_FINGERPRINT_PREVIEW=$(keytool -list -v -keystore "$KEYSTORE_PATH" -alias "$ALIAS" -storepass "$STORE_PASSWORD" 2>/dev/null | sed -n 's/^\s*SHA256:\s*//p' | head -n 1)
  if [[ -z "$STARTUP_GATE_FINGERPRINT_PREVIEW" ]]; then
    STARTUP_GATE_FINGERPRINT_PREVIEW="<SHA256_FROM_KEYSTORE>"
  fi
fi
STARTUP_GATE_CONTENT=$(cat <<EOF
# Auto-generated by scripts/setup-release-signing.sh
# Do NOT commit this file.
startup.gate.expectedPackage=com.github.nomadboxlab.monadbox
startup.gate.expectedAppClass=com.github.yumelira.yumebox.App
startup.gate.expectedAppParent=android.app.Application
startup.gate.releaseFingerprint=$STARTUP_GATE_FINGERPRINT_PREVIEW
startup.gate.enforceSigner=true
startup.gate.enforceApkV2=true
EOF
)

if [[ "$DRY_RUN" == "true" ]]; then
  echo "[signing-setup] Dry-run mode: no file will be written and no build will run."
  echo "[signing-setup] Target signing.properties path: $SIGNING_PROPERTIES_PATH"
  echo "[signing-setup] Planned content:"
  echo "$SIGNING_CONTENT"
  echo "[signing-setup] Target startup-gate.local.properties path: $STARTUP_GATE_PATH"
  echo "[signing-setup] Planned content:"
  echo "$STARTUP_GATE_CONTENT"
  if [[ "$SHOULD_CREATE" == "true" ]]; then
    echo "[signing-setup] Keystore generation would run for: $KEYSTORE_PATH"
  else
    echo "[signing-setup] Keystore generation would be skipped (file already exists)."
  fi
  exit 0
fi

if [[ "$SHOULD_CREATE" == "true" ]]; then
  DNAME="CN=MonadBox, OU=Mobile, O=NomadBoxLab, L=Unknown, S=Unknown, C=CN"
  echo "[signing-setup] Generating keystore: $KEYSTORE_PATH"
  keytool -genkeypair -v \
    -keystore "$KEYSTORE_PATH" \
    -storetype "$STORE_TYPE" \
    -alias "$ALIAS" \
    -keyalg RSA \
    -keysize 2048 \
    -validity "$VALIDITY_DAYS" \
    -storepass "$STORE_PASSWORD" \
    -keypass "$KEY_PASSWORD" \
    -dname "$DNAME"
fi

echo "[signing-setup] Validating keystore alias..."
keytool -list -v -keystore "$KEYSTORE_PATH" -alias "$ALIAS" -storepass "$STORE_PASSWORD" >/dev/null

STARTUP_GATE_FINGERPRINT=$(keytool -list -v -keystore "$KEYSTORE_PATH" -alias "$ALIAS" -storepass "$STORE_PASSWORD" | sed -n 's/^\s*SHA256:\s*//p' | head -n 1)
if [[ -z "$STARTUP_GATE_FINGERPRINT" ]]; then
  echo "Failed to extract SHA256 fingerprint from keystore alias: $ALIAS" >&2
  exit 1
fi

printf '%s\n' "$SIGNING_CONTENT" > "$SIGNING_PROPERTIES_PATH"
echo "[signing-setup] Wrote signing properties: $SIGNING_PROPERTIES_PATH"

STARTUP_GATE_CONTENT=$(cat <<EOF
# Auto-generated by scripts/setup-release-signing.sh
# Do NOT commit this file.
startup.gate.expectedPackage=com.github.nomadboxlab.monadbox
startup.gate.expectedAppClass=com.github.yumelira.yumebox.App
startup.gate.expectedAppParent=android.app.Application
startup.gate.releaseFingerprint=$STARTUP_GATE_FINGERPRINT
startup.gate.enforceSigner=true
startup.gate.enforceApkV2=true
EOF
)
printf '%s\n' "$STARTUP_GATE_CONTENT" > "$STARTUP_GATE_PATH"
echo "[signing-setup] Wrote startup gate config: $STARTUP_GATE_PATH"

if [[ "$SKIP_BUILD" != "true" ]]; then
  echo "[signing-setup] Running release build validation..."
  ./gradlew :app:assembleRelease
fi

echo "[signing-setup] Done."
