name: Dependency Review

on:
  pull_request:
    branches: [ "Monad" ]
    paths-ignore:
      - '**.md'
      - '**.example'
      - 'docs/**'
      - '.clang-format'
      - '.github/kernel-state/**'
      - '.gitignore'

permissions:
  contents: read

concurrency:
  group: dependency-review-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v6
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          deny-licenses: AGPL-1.0-only
